services:
  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6333:6333'
      - '6334:6334'
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: 'prometheus'
    volumes:
      - './prometheus-config.yml:/etc/prometheus/prometheus.yml'
    networks:
      - spring-ai
    ports:
      - '9090:9090'
networks:
  spring-ai:
    driver: bridge